// ---------------------------------------------------------------------------
// Photo catalog.
//
// To add a real photo:
//   1. Drop the image file into  public/photos/
//   2. Add an entry below (or in public/photos/manifest.json) with its path,
//      category, optional bw flag, and a caption.
//
// Each photo has one PRIMARY category. `bw` is a cross-cutting flag — on the
// mind-map, a "b&w" node links to every black & white shot across categories.
// ---------------------------------------------------------------------------

export const CATEGORIES = [
  "concert",
  "action",
  "portraits",
  "life",
  "landscape",
  "film",
] as const;

export type Category = (typeof CATEGORIES)[number];

// Display names for the UI (ids above stay short + lowercase).
export const CATEGORY_LABELS: Record<Category, string> = {
  concert: "concert",
  action: "action / sport",
  portraits: "portraits",
  life: "life",
  landscape: "landscape",
  film: "film",
};

export interface Photo {
  src: string;
  category: Category;
  bw?: boolean;
  caption?: string;
  /** show this photo on the gallery wall (set per-photo in manifest.json) */
  wall?: boolean;
  /** intrinsic size — lets the browser reserve space and avoid layout shift */
  w?: number;
  h?: number;
}

// One manifest file per section (generated by `npm run photos`). Edit captions
// and the `wall` flag in these files — each holds a single category.
import concert from "../../public/photos/manifest/concert.json";
import action from "../../public/photos/manifest/action.json";
import portraits from "../../public/photos/manifest/portraits.json";
import life from "../../public/photos/manifest/life.json";
import landscape from "../../public/photos/manifest/landscape.json";
import film from "../../public/photos/manifest/film.json";

type SectionEntry = Omit<Photo, "category">;
const sections: Record<Category, SectionEntry[]> = {
  concert,
  action,
  portraits,
  life,
  landscape,
  film,
};

// category is implied by which file an entry lives in
export const photos: Photo[] = CATEGORIES.flatMap((cat) =>
  sections[cat].map((p) => ({ ...p, category: cat }))
);
